/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2014 Christian Gärtner
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package io.github.achtern.AchternEngine.core.input;

/**
 * A Key on the Keyboard
 */
public enum Key {
    NONE,
    ESCAPE,
    N_1,
    N_2,
    N_3,
    N_4,
    N_5,
    N_6,
    N_7,
    N_8,
    N_9,
    N_0,
    MINUS,
    EQUALS,
    BACK,
    TAB,
    Q,
    W,
    E,
    R,
    T,
    Y,
    U,
    I,
    O,
    P,
    LBRACKET,
    RBRACKET,
    RETURN,
    LCONTROL,
    A,
    S,
    D,
    F,
    G,
    H,
    J,
    K,
    L,
    SEMICOLON,
    APOSTROPHE,
    GRAVE,
    LSHIFT,
    BACKSLASH,
    Z,
    X,
    C,
    V,
    B,
    N,
    M,
    COMMA,
    PERIOD,
    SLASH,
    RSHIFT,
    MULTIPLY,
    LMENU,
    LALT,
    SPACE,
    CAPITAL,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    NUMLOCK,
    SCROLL,
    NUMPAD7,
    NUMPAD8,
    NUMPAD9,
    SUBTRACT,
    NUMPAD4,
    NUMPAD5,
    NUMPAD6,
    ADD,
    NUMPAD1,
    NUMPAD2,
    NUMPAD3,
    NUMPAD0,
    DECIMAL,
    F11,
    F12,
    F13,
    F14,
    F15,
    KANA,
    CONVERT,
    NOCONVERT,
    YEN,
    NUMPADEQUALS,
    CIRCUMFLEX,
    AT,
    COLON,
    UNDERLINE,
    KANJI,
    STOP,
    AX,
    UNLABELED,
    NUMPADENTER,
    RCONTROL,
    NUMPADCOMMA,
    DIVIDE,
    SYSRQ,
    RMENU,
    RALT,
    PAUSE,
    HOME,
    UP,
    PRIOR,
    LEFT,
    RIGHT,
    END,
    DOWN,
    NEXT,
    INSERT,
    DELETE,
    LMETA,
    LWIN,
    RMETA,
    RWIN,
    APPS,
    POWER,
    SLEEP
}
